#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo "Usage: cmd [-1] [-2] [-3]" >&2
    exit 0
fi

ADDR="localhost/#world1"

while getopts ":123" opt; do
  case $opt in
    1)
      ADDR="localhost/#world1"
      ;;
    2)
      ADDR="localhost/#world2"
      ;;
    3)
      ADDR="localhost/#world3"
      ;;
   \?)
      echo "Usage: cmd [-1] [-2] [-3]" >&2
      exit 0
      ;;
  esac
done

echo "Launching $ADDR simulation!"

export DISPLAY=:0

chromium-browser --kiosk localhost/#world1 >/dev/null&
unclutter -idle 0.1 -root >/dev/null&
