#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo "Usage: cmd [-1] [-2] [-3]" >&2
    exit 0
fi

ADDR="http://localhost/#world1"

while getopts ":123" opt; do
  case $opt in
    1)
      ADDR="http://localhost/#world1"
      ;;
    2)
      ADDR="http://localhost/#world2"
      ;;
    3)
      ADDR="http://localhost/#world3"
      ;;
   \?)
      echo "Usage: cmd [-1] [-2] [-3]" >&2
      exit 0
      ;;
  esac
done

echo "Launching $ADDR simulation!"

export DISPLAY=:0

unclutter -idle 0.1 -root
chromium-browser --kiosk $ADDR
